services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravelbp-app
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
    networks:
      - laravelbp-network

  web:
    image: nginx:alpine
    container_name: laravelbp-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravelbp-network

  db:
    image: mariadb:10.11
    container_name: laravelbp-db
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - laravelbp-network

  redis:
    image: redis:alpine
    container_name: laravelbp-redis
    networks:
      - laravelbp-network

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: laravelbp-node
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - laravelbp-network

networks:
  laravelbp-network:
    driver: bridge